# Generated by Django 3.2.22 on 2024-02-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('assign_id', models.AutoField(db_column='Assign_id', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='Status', max_length=45)),
            ],
            options={
                'db_table': 'assign',
                'managed': False,
            },
        ),
    ]
