# Generated by Django 3.2.22 on 2024-02-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(db_column='Bill_id', primary_key=True, serialize=False)),
                ('nameofexaminer', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45)),
                ('billcol', models.CharField(db_column='Billcol', max_length=45)),
                ('total_no_of_paper_value', models.CharField(max_length=45)),
                ('mandatory_deduction', models.CharField(max_length=45)),
                ('elligibel_no_of_paper', models.CharField(db_column='Elligibel_no_of_paper', max_length=45)),
                ('remunaration', models.CharField(db_column='Remunaration', max_length=45)),
                ('additional_maximum_chairman_fee', models.CharField(db_column='Additional_maximum_chairman_fee', max_length=45)),
                ('total', models.CharField(db_column='Total', max_length=45)),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
    ]
