# Generated by Django 3.2.22 on 2024-02-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=45)),
                ('phone_no', models.CharField(max_length=45)),
                ('college_name', models.CharField(max_length=45)),
                ('experience', models.CharField(db_column='Experience', max_length=45)),
                ('choice', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'form',
                'managed': False,
            },
        ),
    ]
