# Generated by Django 3.2.22 on 2024-02-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheif',
            fields=[
                ('cheif_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email_id', models.CharField(max_length=45)),
                ('phone_no', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cheif',
                'managed': False,
            },
        ),
    ]
