# Generated by Django 3.2.22 on 2024-02-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('from_field', models.IntegerField(db_column='from')),
                ('to', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'work',
                'managed': False,
            },
        ),
    ]
