# Generated by Django 3.2.22 on 2024-02-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additionals',
            fields=[
                ('additional_id', models.AutoField(db_column='Additional_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='User_name', max_length=45)),
                ('password', models.CharField(db_column='Password', max_length=45)),
                ('email_id', models.CharField(db_column='Email_id', max_length=45)),
                ('phone_no', models.CharField(db_column='Phone_no', max_length=45)),
                ('uid', models.IntegerField()),
                ('sem', models.CharField(max_length=45)),
                ('priority_1', models.CharField(max_length=45)),
                ('priority_2', models.CharField(max_length=45)),
                ('priority_3', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'additionals',
                'managed': False,
            },
        ),
    ]
