# Generated by Django 3.2.22 on 2024-02-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(db_column='Paper_id', primary_key=True, serialize=False)),
                ('sem', models.CharField(max_length=45)),
                ('paper', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'paper',
                'managed': False,
            },
        ),
    ]
